---
title: MSHS COVID-19 Vaccine Schedule Tracking
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
---
  
<!-- ### MSHS COVID-19 Vaccine Dose 3 Schedule Tracking -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r Install and load packages}
# Code for updating data analysis for afternoon huddle

#Install and load necessary packages --------------------
#install.packages("readraw_dfl")
#install.packages("writeraw_dfl")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("svDialogs")
#install.packages("stringr")
#install.packages("formattable")
#install.packages("ggpubr")
#install.packages("zipcodeR")
#install.packages("tidyr")
#install.packages("janitor")
#install.packages("knitr")
#install.packages("rmarkdown")
#install.packages("kableExtra")

#Analysis for weekend discharge tracking
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(dplyr)
library(reshape2)
library(svDialogs)
library(stringr)
library(formattable)
library(scales)
library(ggpubr)
library(reshape2)
library(knitr)
library(kableExtra)
library(rmarkdown)
library(zipcodeR)
library(tidyr)
library(janitor)
library(knitr)
library(rmarkdown)
library(kableExtra)
```

```{r Import schedule data and reference data}
# Set path for file selection
user_path <- paste0(user_directory, "\\*.*")

# Determine whether or not to update an existing repo
initial_run <- FALSE
update_repo <- TRUE

# Determine whether or not to update walk-in analysis
update_walkins <- FALSE

# Import reference data for site and pod mappings
site_mappings <- read_excel(paste0(user_directory, "/ScheduleData/",
                                   "Automation Ref 2021-11-22.xlsx"),
                            sheet = "Site Mappings")
pod_mappings <- read_excel(paste0(user_directory, "/ScheduleData/",
                                  "Automation Ref 2021-11-22.xlsx"),
                           sheet = "Pod Mappings Simple")

# MSHS color scheme
sinai_colors <- c("#221f72", "#C4C3EF",
                  "#00AEEF", "#B3EBFF",
                  "#D80B8C", "#FBB6E2",
                  "#7F7F7F")

# Store today's date
today <- Sys.Date()

# Create dataframe with dates and weeks
all_dates <- data.frame("Date" = seq.Date(as.Date("1/1/20",
                                                  format = "%m/%d/%y"),
                                          as.Date("12/31/21",
                                                  format = "%m/%d/%y"),
                                          by = 1))
all_dates <- all_dates %>%
  mutate(Year = year(Date),
         WeekNum = format(Date, "%U"))

# Site order
all_sites <- c("MSB",
               "MSBI",
               "MSH",
               "MSM",
               "MSQ",
               "MSW",
               "MSVD",
               "Network LI")

# Vaccine types
vax_types <- c("Adult", "Peds")

report_run_time <- ifelse(hour(Sys.time()) > 14, "PM", "AM")

sched_data_file <- choose.files(
  default =
    paste0(user_directory,
           ifelse(report_run_time == "AM",
                  "/Epic Auto Report Sched All Status/*.*",
                  "/Epic PM Huddle Sched All Status/*.*")),
      caption = "Select current Epic schedule")

report_date <- date(file.info(sched_data_file)$ctime)

raw_data <- read.csv(sched_data_file,
                     stringsAsFactors = FALSE,
                     check.names = FALSE)

# raw_data[, ncol(raw_data)] <- NULL

```

```{r Format and preprocess raw schedule data}
sched_data <- raw_data %>%
  filter(Patient != "Patient, Test") %>%
  rename(MadeDate = `Made Date`,
         IsPtEmployee = `Is the patient a Mount Sinai employee`) %>%
  mutate(DOB = as.Date(DOB, format = "%m/%d/%Y"),
         MadeDate = as.Date(MadeDate, format = "%m/%d/%y"),
         ApptDate = as.Date(Date, format = "%m/%d/%Y"),
         # Clean up department if it is duplicated in that column
         Department = ifelse(str_detect(Department, ","),
                        substr(Department, 1,
                               str_locate(Department, ",") - 1),
                        Department),
         # Group arrived, completed, and checked out appointments as arrived
         Status = ifelse(`Appt Status` %in% c("Arrived", "Comp", "Checked Out"),
                         "Arr", `Appt Status`),
         # Update appointment status: classify any appts from prior days that are
         # still in scheduled as No Shows
         Status2 = ifelse(ApptDate < (today) & Status == "Sch", "No Show", 
                          # Correct any appts erroneously marked as arrived early
                          ifelse((report_date < today &
                                    ApptDate >= today &
                                    Status == "Arr") |
                                   (ApptDate > today & Status == "Arr"), "Sch",
                                 Status)),
         # Determine whether the vaccine is an adult or pediatric dose
         VaxType = ifelse(Department %in% c("1468 MADISON PEDIATRIC VACCINE POD") |
                            `Provider/Resource` %in% c("DOSE 1 PEDIATRIC [1324684]",
                                                       "DOSE 2 PEDIATRIC [1324685]"),
                          "Peds", "Adult"),
         # Determine whether appointment is for dose 1, 2, or 3 based on
         # scheduled visit type
         Dose = ifelse(str_detect(Type, "DOSE 1"), 1,
                       ifelse(str_detect(Type, "DOSE 2"), 2,
                              ifelse(str_detect(Type, "DOSE 3"), 3, NA))))

# Crosswalk sites
sched_data <- left_join(sched_data, site_mappings,
                        by = c("Department" = "Department"))


```

```{r Create template of sites and dates}
# Create dataframe of dates for next 2 weeks
dates_2wks <- seq.Date(from = today - 1,
                       to = today + 14,
                       by = 1)

dates_templ <- data.frame(
  "Date" = rep(dates_2wks,
               length(all_sites)),
   stringsAsFactors = FALSE)

dates_templ <- dates_templ %>%
  arrange(Date)

# Create dataframe of doses
all_doses <- seq(from = 1, to = 3, by = 1)

doses_templ <- data.frame(
  "Dose" = rep(all_doses,
               length(all_sites)))

doses_templ <- doses_templ %>%
  arrange(Dose)

# Create a dataframe of vaccine types
vax_type_templ <- data.frame(
  "VaxType" = rep(vax_types,
                  length(all_sites)),
  stringsAsFactors = FALSE
)

vax_type_templ <- vax_type_templ %>%
  arrange(VaxType)

# Combine site and dates
site_dates_templ <- data.frame(
  "Site" = rep(all_sites, length(dates_2wks)),
  "Date" = dates_templ,
  stringsAsFactors = FALSE)

# Combine site and doses
site_doses_templ <- data.frame(
  "Site" = rep(all_sites, length(all_doses)),
  "Dose" = doses_templ,
  stringsAsFactors = FALSE)

# Combine site and vaccine types
site_vax_templ <- data.frame(
  "Site" = rep(all_sites, length(vax_types)),
  "VaxType" = vax_type_templ,
  stringsAsFactors = FALSE
)

site_vax_templ <- site_vax_templ %>%
  filter(VaxType %in% c("Adult") |
           (VaxType %in% c("Peds") & Site %in% c("MSH", "MSBI")))

site_date_dose_templ <- left_join(site_dates_templ,
                                  site_doses_templ,
                                  by = c("Site" = "Site"))

site_vax_dose_templ <- left_join(site_vax_templ,
                                 site_doses_templ,
                                 by = c("Site" = "Site"))

site_vax_dose_templ <- site_vax_dose_templ %>%
  filter(!(VaxType %in% c("Peds") & Dose %in% c(3)))

# Combine site, dose, date, and vaccine type
site_date_vax_dose_templ <- left_join(site_date_dose_templ,
                                      site_vax_dose_templ,
                                      by = c("Site" = "Site",
                                             "Dose" = "Dose"))

```

```{r Summarize schedule data by day and dose}
sched_summary <- sched_data %>%
  filter(Status2 %in% c("Arr", "Sch") &
           ApptDate %in% dates_2wks) %>%
  group_by(Dose, Site, VaxType, Status2, ApptDate) %>%
  summarize(Count = n(), .groups = "keep")

sched_summary <- left_join(site_date_vax_dose_templ,
                           sched_summary,
                           by = c("Site" = "Site",
                                  "Date" = "ApptDate",
                                  "VaxType" = "VaxType",
                                  "Dose" = "Dose"))

sched_summary <- sched_summary %>%
  mutate(Count = replace_na(Count, 0),
         Status2 = ifelse(is.na(Status2) & Date < today, "Arr",
                          ifelse(is.na(Status2) & Date >= today, "Sch",
                                 Status2))) %>%
  arrange(VaxType, Site, Date, Dose, Status2) %>%
  mutate(
    # Date = format(Date, "%m/%d/%y"),
         Dose = paste0("Dose", Dose))

sched_summary_table <- sched_summary %>%
  pivot_wider(names_from = c(Status2, VaxType, Dose, Date),
              names_sep = "_",
              names_sort = FALSE,
              values_from = Count) %>%
  adorn_totals(where = "row",
               na.rm = TRUE,
               name = "MSHS") %>%
  pivot_longer(cols = contains("_"),
               names_to = c("Status2", "VaxType", "Dose", "Date"),
               names_sep = "_",
               values_to = "Count") %>%
  # arrange(Site, Date, Status2) %>%
  pivot_wider(names_from = c(Site, Status2, VaxType, Date),
              names_sep = "_",
              names_sort = FALSE,
              values_from = Count) %>%
  adorn_totals(where = "row",
               na.rm = TRUE,
               name = "AllDoses") %>%
  pivot_longer(cols = contains("_"),
               names_to = c("Site", "Status2", "VaxType", "Date"),
               names_sep = "_",
               values_to = "Count") %>%
  filter(VaxType %in% c("Adult") |
           (VaxType %in% c("Peds") & Site %in% c("MSH", "MSBI", "MSHS"))) %>%
  mutate(Site = factor(Site, levels = c(all_sites, "MSHS"), ordered = TRUE),
         Dose = factor(Dose, levels = c("Dose1", "Dose2", "Dose3", "AllDoses")),
         Count = replace_na(Count, 0),
         Date = as.Date(Date, format = "%Y-%m-%d")) %>%
  arrange(VaxType, Site, Date, Status2) %>%
  mutate(Date = format(Date, "%m/%d/%y")) %>%
  pivot_wider(names_from = c(Status2, Date),
              names_sep = "_",
              names_sort = FALSE,
              values_from = Count) %>%
  adorn_totals(where = "col",
               na.rm = TRUE,
               name = "Total")

```

```{r Create a kable for each dose}

sched_data_kable <- function(vax_type, dose) {
  kable_vax_type <- vax_type
  
  kable_dose <- dose
  
  kable_dose_title <- ifelse(dose == "AllDoses", "All Doses",
                             str_replace(kable_dose, "Dose", "Dose "))
  
  sched_kable_df <- sched_summary_table %>%
  filter(VaxType == kable_vax_type,
           Dose == kable_dose) %>%
  mutate(VaxType = NULL,
         Dose = NULL)
  
  sched_summary_cols <- colnames(sched_kable_df)
  sched_summary_table_names <- str_replace(sched_summary_cols,
                                           regex("^[a-z]*_",
                                                 ignore_case = TRUE),
                                           "")
  
  arr_cols <- max(which(str_detect(sched_summary_cols, "Arr"))) -
    min(which(str_detect(sched_summary_cols, "Arr"))) + 1
  
  sch_cols <- max(which(str_detect(sched_summary_cols, "Sch"))) -
    min(which(str_detect(sched_summary_cols, "Sch"))) + 1
  
  sched_kable <- kable(sched_kable_df,
                       format = "html",
                       escape = FALSE,
                       align = "c",
                       digits = 0,
                       caption = paste(kable_vax_type, kable_dose_title, "Schedule"),
                       col.names = sched_summary_table_names) %>%
    kable_styling(bootstrap_options = "hover",
                  position = "center",
                  font_size = 11,
                  full_width = FALSE) %>%
    column_spec(column = c(1,
                           ncol(sched_kable_df) - 1,
                           ncol(sched_kable_df)),
                border_right = "thin solid lightgray") %>%
    add_header_above(c(" " = 1,
                       "Arrived Visits" = arr_cols,
                       "Scheduled Visits" = sch_cols,
                       " " = 1),
                     background = c("",
                                    sinai_colors[1],
                                    sinai_colors[3],
                                    ""),
                     line = FALSE,
                     color = "white") %>%
    row_spec(row = nrow(sched_kable_df),
             bold = TRUE,
             italic = TRUE,
             hline_after = TRUE) %>%
    column_spec(column = ncol(sched_kable_df),
                bold = TRUE,
                italic = TRUE) %>%
    scroll_box(width = "800px")
  
  return(sched_kable)
}

```


```{r Subset dose 3 appointments made yesterday and today for all appointment statuses}
# Summarize all appointments made yesterday and today, regardless of appointment status
dose3_sch_made_date <- sched_data %>%
  filter(MadeDate %in% seq.Date(today - 1, today, by = 1) &
           ApptDate %in% dates_2wks &
           Dose == 3)

made_dates <- sort(unique(dose3_sch_made_date$MadeDate))

made_dates_str <- ifelse(length(made_dates) == 1,
                         format(made_dates, "%m/%d/%y"),
                         paste(format(min(made_dates), "%m/%d/%y"),
                                "to",
                               format(max(made_dates), "%m/%d/%y")))

dose3_made_date_all_status <- dose3_sch_made_date %>%
  group_by(Site, ApptDate) %>%
  summarize(Count = n())

dose3_made_date_all_status <- left_join(
  site_dates_templ,
  dose3_made_date_all_status,
  by = c("Site" = "Site",
         "Date" = "ApptDate")
)

dose3_made_date_all_status <- dose3_made_date_all_status %>%
  mutate(Count = replace_na(Count, 0),
         Date = format(Date, "%m/%d/%y"))

dose3_made_date_all_status_cast <- pivot_wider(
  dose3_made_date_all_status,
  names_from = Date,
  values_from = Count,
  names_sort = FALSE
)

dose3_made_date_all_status_cast <- dose3_made_date_all_status_cast %>%
  adorn_totals(where = "row",
               na.rm = TRUE,
               name = "MSHS") %>%
  adorn_totals(where = "col",
               na.rm = TRUE,
               name = "Total")



kable_dose3_made_date_all_status <- 
  kable(dose3_made_date_all_status_cast,
        format = "html",
        escape = FALSE,
        align = "c",
        digits = 0,
        caption = "All Appointment Statuses Including Cancellations & No Shows") %>%
  kable_styling(bootstrap_options = "hover",
                position = "center",
                font_size = 11,
                full_width = FALSE) %>%
  column_spec(column = c(1,
                         ncol(dose3_made_date_all_status_cast) -1,
                         ncol(dose3_made_date_all_status_cast)),
                border_right = "thin solid lightgray") %>%
  add_header_above(c(" " = 1,
                     "Appointment Date" =
                       ncol(dose3_made_date_all_status_cast) - 1),
                     background = c("",
                                    sinai_colors[1]),
                     line = FALSE,
                     color = "white") %>%
  row_spec(row = nrow(dose3_made_date_all_status_cast),
           bold = TRUE,
           italic = TRUE,
           hline_after = TRUE) %>%
  column_spec(column = ncol(dose3_made_date_all_status_cast),
              bold = TRUE,
              italic = TRUE) %>%
  scroll_box(width = "800px")

```

```{r Further subset dose 3 appointment made yesterday and today to only include arrived and scheduled appointments}
dose3_made_date_arr_sch <- dose3_sch_made_date %>%
  filter(Status2 %in% c("Arr", "Sch")) %>%
  group_by(Site, ApptDate) %>%
  summarize(Count = n())

dose3_made_date_arr_sch <- left_join(
  site_dates_templ,
  dose3_made_date_arr_sch,
  by = c("Site" = "Site",
         "Date" = "ApptDate")
)

dose3_made_date_arr_sch <- dose3_made_date_arr_sch %>%
  mutate(Count = replace_na(Count, 0),
         Date = format(Date, "%m/%d/%y"))

dose3_made_date_arr_sch_cast <- pivot_wider(
  dose3_made_date_arr_sch,
  names_from = Date,
  values_from = Count,
  names_sort = FALSE
)

dose3_made_date_arr_sch_cast <- dose3_made_date_arr_sch_cast %>%
  adorn_totals(where = "row",
               na.rm = TRUE,
               name = "MSHS") %>%
  adorn_totals(where = "col",
               na.rm = TRUE,
               name = "Total")

kable_dose3_made_date_arr_sch <-
  kable(dose3_made_date_arr_sch_cast,
        format = "html",
        escape = FALSE,
        align = "c",
        digits = 0,
        caption = "Arrived & Scheduled Appointments Only") %>%
  kable_styling(bootstrap_options = "hover",
                position = "center",
                font_size = 11,
                full_width = FALSE) %>%
  column_spec(column = c(1,
                         ncol(dose3_made_date_arr_sch_cast) -1,
                         ncol(dose3_made_date_arr_sch_cast)),
                border_right = "thin solid lightgray") %>%
  add_header_above(c(" " = 1,
                     "Appointment Date" =
                       ncol(dose3_made_date_arr_sch_cast) - 1),
                     background = c("",
                                    sinai_colors[1]),
                     line = FALSE,
                     color = "white") %>%
  row_spec(row = nrow(dose3_made_date_arr_sch_cast),
           bold = TRUE,
           italic = TRUE,
           hline_after = TRUE) %>%
  column_spec(column = ncol(dose3_made_date_arr_sch_cast),
              bold = TRUE,
              italic = TRUE) %>%
  scroll_box(width = "800px")


```

## Adult Vaccine Schedules by Dose

### All Doses
```{r Call custom function for schedule for all adult doses}
sched_data_kable(vax_type = "Adult", dose = "AllDoses")

```

<br>

### Dose 1
```{r Call custom function for schedule for adult dose 1 appointments}
sched_data_kable(vax_type = "Adult", dose = "Dose1")

```

<br>

### Dose 2
```{r Call custom function for schedule for adult dose 2 appointments}
sched_data_kable(vax_type = "Adult", dose = "Dose2")

```

<br>

### Dose 3
```{r Call custom function for schedule for adult dose 3 appointments}
sched_data_kable(vax_type = "Adult", dose = "Dose3")

```
<br>
<br>

## Peds Vaccine Schedules by Dose

<!-- ### All Doses -->
<!-- ```{r Call custom function for schedule for all peds doses} -->
<!-- sched_data_kable(vax_type = "Peds", dose = "AllDoses") -->

<!-- ``` -->

<br>

### All Doses
```{r Call custom function for schedule for all peds appointments}
sched_data_kable(vax_type = "Peds", dose = "AllDoses")

```

<br>

### Dose 1
```{r Call custom function for schedule for peds dose 1 appointments}
sched_data_kable(vax_type = "Peds", dose = "Dose1")

```

### Dose 2
```{r Call custom function for schedule for peds dose 2 appointments}
sched_data_kable(vax_type = "Peds", dose = "Dose2")

```

<br>

<!-- ### Dose 2 -->
<!-- ```{r Call custom function for schedule for peds dose 2 appointments} -->
<!-- sched_data_kable(vax_type = "Peds", dose = "Dose2") -->

<!-- ``` -->

<!-- <br> -->
<!-- <br> -->

<!-- ## Adult Appts Made Yesterday & Today -->

<!-- ### Dose 3 Appts: All Statuses (Made on `r made_dates_str`) -->
<!-- ```{r Create kable for scheduled appointments over next 14 days} -->

<!-- # asis_output(paste0("<h4>Based on Epic schedule data as of ", -->
<!-- #                    format(file.info(sched_data_file)$ctime, -->
<!-- #                           "%m/%d/%y %I:%M %p"), -->
<!-- #                    "</h4>")) -->
<!-- #  -->
<!-- # asis_output("<br>") -->
<!-- # asis_output("<h4>Dose 3 Schedule for Next Two Weeks</h4>") -->
<!-- # kable_dose3_sch -->
<!-- #  -->
<!-- # asis_output("<br>") -->
<!-- # asis_output("<br>") -->
<!-- # asis_output(paste0("<h4>Dose 3 Schedule for Appointments Made On ", -->
<!-- #                    made_dates_str, -->
<!-- #                    "</h4>")) -->

<!-- kable_dose3_made_date_all_status -->

<!-- asis_output("<br>") -->

<!-- ``` -->

<!-- ### Dose 3 Appts: Arrived & Scheduled Only (Made on `r made_dates_str`) -->
<!-- ```{r Test} -->

<!-- kable_dose3_made_date_arr_sch -->

<!-- asis_output("<h6><i>End of report.</i></h6>") -->

<!-- ``` -->

<h6><i>End of report.</i></h6>