---
  title: "MSHS COVID-19 Vaccinations"
output: html_document
---
  
  ```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r Install and load packages}
# Code for updating data analysis for afternoon huddle

#Install and load necessary packages --------------------
#install.packages("readraw_dfl")
#install.packages("writeraw_dfl")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("svDialogs")
#install.packages("stringr")
#install.packages("formattable")
#install.packages("ggpubr")
#install.packages("zipcodeR")
#install.packages("tidyr")
#install.packages("janitor")
#install.packages("knitr")
#install.packages("rmarkdown")
#install.packages("kableExtra")



#Analysis for weekend discharge tracking
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(dplyr)
library(reshape2)
library(svDialogs)
library(stringr)
library(formattable)
library(scales)
library(ggpubr)
library(reshape2)
library(knitr)
library(kableExtra)
library(rmarkdown)
library(zipcodeR)
library(tidyr)
library(janitor)
library(knitr)
library(rmarkdown)
library(kableExtra)
```

```{r Import reference data, set variables, and import raw data, include = FALSE}

# Set working directory and select raw data ----------------------------
rm(list = ls())

# Determine path for working directory
if ("Presidents" %in% list.files("J://")) {
  user_directory <- paste0("J:/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/",
                           "System Operations/COVID Vaccine")
} else {
  user_directory <- paste0("J:/deans/Presidents/HSPI-PM/",
                           "Operations Analytics and Optimization/Projects/",
                           "System Operations/COVID Vaccine")
}

# Set path for file selection
user_path <- paste0(user_directory, "\\*.*")


# Determine whether or not to update an existing repo
initial_run <- FALSE
update_repo <- FALSE

# Import reference data for site and pod mappings
site_mappings <- read_excel(paste0(user_directory, "/ScheduleData/",
                                   "Automation Ref 2021-05-03.xlsx"),
                            sheet = "Site Mappings")
pod_mappings <- read_excel(paste0(user_directory, "/ScheduleData/",
                                  "Automation Ref 2021-05-03.xlsx"),
                           sheet = "Pod Mappings Simple")

# Store today's date
# today <- Sys.Date()
today <- as.Date("3/31/21", format = "%m/%d/%y")

# Site order
all_sites <- c("MSB",
               "MSBI",
               "MSH",
               "MSM",
               "MSQ",
               "MSW",
               "MSVD",
               "Network LI",
               "MSSN")

# Pod type order
pod_type <- c("Employee", "Patient", "All")

# Vaccine manufacturers
mfg <- c("Pfizer", "Moderna", "J&J")

# NY zip codes
ny_zips <- search_state("NY")

# First vaccine date
vacc_start_date <- as.Date("12/15/20", format = "%m/%d/%y")
vacc_start_first_sun <- vacc_start_date - (wday(vacc_start_date) - 1)

# Determine current week of vaccine effort
this_week <- as.numeric(floor((today - vacc_start_first_sun) / 7) + 1)

# Create dataframe with dates and weeks since vaccines started
all_dates <- data.frame("Date" = seq.Date(as.Date("12/15/20",
                                                  format = "%m/%d/%y"),
                                          today + 7,
                                          by = 1))

all_dates <- all_dates %>%
  mutate(VaccWeek = as.numeric(
    floor((Date - vacc_start_first_sun) / 7) + 1))

vacc_week_dates <- all_dates %>%
  group_by(VaccWeek) %>%
  summarize(Dates = 
              paste0(format(min(Date), "%m/%d/%y"),
                     "-",
                     format(max(Date), "%m/%d/%y")))

# Create variable with doses
doses <- c("Dose1", "Dose2", "AllDoses")

# Specify Sinai colors for table
sinai_colors <- c("#221f72", "#C4C3EF",
                  "#00AEEF", "#B3EBFF",
                  "#D80B8C", "#FBB6E2") #,
# "#4C4D4C", "#8988dd", "#B2B3B2", "#F887CE")

# Import raw data from Epic
if (update_repo) {
  sched_repo <- readRDS(
    choose.files(default = paste0(user_directory,
                                  "/R_Sched_AM_Repo/*.*"),
                 caption = "Select this morning's schedule repository"))
  
  raw_df <- read.csv(choose.files(
    default =
      paste0(user_directory, "/Epic PM Huddle Sched All Status/*.*"),
    caption = "Select this afternoon's Epic schedule"),
    stringsAsFactors = FALSE,
    check.names = FALSE)
  
  new_sched <- raw_df
  
  # Remove test patient
  new_sched <- new_sched[new_sched$Patient != "Patient, Test", ]
  
  # Update data classes from .csv schedule import to match repository structure
  new_sched <- new_sched %>%
    mutate(DOB = as.Date(DOB, format = "%m/%d/%Y"),
           `Made Date` = as.Date(`Made Date`, format = "%m/%d/%y"),
           Date = as.Date(Date, format = "%m/%d/%Y"),
           `Appt Time` = as.POSIXct(paste("1899-12-31 ", `Appt Time`),
                                    tz = "", format = "%Y-%m-%d %H:%M %p"),
           `ZIP Code` = substr(`ZIP Code`, 2, nchar(`ZIP Code`)))
  
  # Determine dates in new report
  current_dates <- sort(unique(new_sched$Date))
  
  # Update schedule repository by removing duplicate dates and adding data
  # from new report
  sched_repo <- sched_repo %>%
    filter(!(Date >= current_dates[1]))
  sched_repo <- rbind(sched_repo, new_sched)
  
  # Save schedule
  saveRDS(sched_repo, paste0(user_directory, "/R_Sched_PM_Huddle_Repo/",
                             "Epic Sched 340PM ",
                             format(min(sched_repo$Date), "%m%d%y"), " to ",
                             format(max(sched_repo$Date), "%m%d%y"),
                             " on ", format(Sys.time(), "%m%d%y %H%M"), ".rds"))
  
} else {
  
  sched_repo <- readRDS(
    choose.files(default = paste0(user_directory,
                                  "/R_Sched_PM_Huddle_Repo/*.*"),
                 caption = "Select the desired schedule repository"))
  
}

# Import MSSN data from Tableau
# mssn_employee <- read_excel(
#   path = choose.files(
#     default = paste0(user_directory, "/MSSN Tableau Doses/*.*"),
#     caption = "Select MSSN Tableau Administration Data for Employees"),
#   col_names = TRUE,
#   na = c("", NA),
#   skip = 1)
# 
# mssn_nonemployee <- read_excel(
#   path = choose.files(
#     default = paste0(user_directory, "/MSSN Tableau Doses/*.*"),
#     caption = "Select MSSN Tableau Administration Data for Non-Employees"),
#   col_names = TRUE,
#   na = c("", NA),
#   skip = 1)
# 
# mssn_employee <- mssn_employee[1:nrow(mssn_employee) - 1, ]
# mssn_nonemployee <- mssn_nonemployee[1:nrow(mssn_nonemployee) - 1, ]
# 
# mssn_employee <- mssn_employee %>%
#   mutate(`Pod Type` = "Employee")
# 
# mssn_nonemployee <- mssn_nonemployee %>%
#   mutate(`Pod Type` = "Patient")
# 
# mssn_admin <- rbind(mssn_employee, mssn_nonemployee)

# Import MSSN data from Tableau
mssn_admin <- read_excel(
  path = choose.files(
    default = paste0(user_directory, "/MSSN Tableau Doses/*.*"),
    caption = "Select MSSN Tableau Administration Data"),
  col_names = TRUE,
  na = c("", NA),
  skip = 1)

mssn_admin <- mssn_admin[1:nrow(mssn_admin) - 1, ]

colnames(mssn_admin) <- c("ApptDate", "Dose1", "Dose2", "AllDoses")

mssn_admin$Mfg <- "Pfizer"
```

```{r Format Epic schedule data}
# Format and analyze Epic schedule to date for dashboards ---------------------
epic_sched_to_date <- sched_repo

epic_sched_to_date <- epic_sched_to_date %>%
  mutate(
    # Determine whether appointment is for dose 1 or dose 2
    Dose = ifelse(str_detect(Type, "DOSE 1"), "Dose1",
                  ifelse(str_detect(Type, "DOSE 2"), "Dose2", NA)),
    # Determine appointment date, year, month, etc.
    ApptDate = date(Date),
    ApptYear = year(Date),
    ApptMonth = month(Date),
    ApptDay = day(Date),
    ApptWeek = week(Date),
    # Clean up department if it is duplicated in that column
    Department = ifelse(str_detect(Department, ","),
                        substr(Department, 1,
                               str_locate(Department, ",") - 1),
                        Department),
    # Group arrived, completed, and checked out appts as arrived
    Status = ifelse(`Appt Status` %in% c("Arrived", "Comp", "Checked Out"),
                    "Arr", `Appt Status`),
    # Update appointment status: classify any appts from prior days that are
    # still in scheduled as No Shows
    Status2 = ifelse(ApptDate < (today) & Status == "Sch", "No Show", Status),
    # Determine manufacturer based on immunization field
    Mfg = #Keep manufacturer as NA if the appointment hasn't been arrived
      ifelse(Status2 != "Arr", NA,
             # Assume any visits without immunization record are Pfizer
             ifelse(is.na(Immunizations), "Pfizer",
                    # Any immunizations with Moderna in text classified as
                    # Moderna, otherwise Pfizer
                    ifelse(str_detect(Immunizations, "Moderna"), "Moderna",
                           # Any immunizations with Johnson and Johnson are
                           # classified as J&J
                           ifelse(str_detect(Immunizations,
                                             "Johnson and Johnson"),
                                  "J&J", "Pfizer")))),
    # Determine week number of year
    WeekNum = format(ApptDate, "%U"),
    # Determine appointment day of week
    DOW = weekdays(ApptDate),
    # Determine if patient's zip code is in NYS
    NYZip = substr(`ZIP Code`, 1, 5) %in% ny_zips$zipcode,
    # Determine week number of vaccine efforts
    VaccWeek = as.numeric(floor((ApptDate - vacc_start_first_sun) / 7) + 1))

# Crosswalk sites
epic_sched_to_date <- left_join(epic_sched_to_date, site_mappings,
                                by = c("Department" = "Department"))

# Update data based on site nuances
epic_sched_to_date <- epic_sched_to_date %>%
  mutate(
    # Roll up any Moderna administered at MSB for YWCA to MSH
    Site = ifelse(Site %in% c("MSB") & Mfg %in% c("Moderna"), "MSH", Site),
    # Update all MSVD visits to J&J
    Mfg = ifelse(Site %in% c("MSVD"), "J&J", Mfg))

# Crosswalk pod type (employee vs patient)
epic_sched_to_date <- left_join(epic_sched_to_date,
                                pod_mappings[, c("Provider", "Pod Type")],
                                by = c("Provider/Resource" = "Provider"))

# Assume any pods without a mapping are patient pods
epic_sched_to_date[is.na(epic_sched_to_date$`Pod Type`), "Pod Type"] <- "Patient"

# Determine expected manufacturer for scheduled appointments
dose1_moderna <- epic_sched_to_date %>%
  filter(Status2 %in% c("Arr") & Mfg == "Moderna" & Dose == "Dose1") %>%
  select(MRN)

epic_sched_to_date <- epic_sched_to_date %>%
  mutate(ExpSchMfg = ifelse(Status2 != "Sch", NA,
                            ifelse(Site == "MSVD", "J&J",
                                   ifelse(Dose == 'Dose1', "Pfizer",
                                          ifelse(MRN %in% dose1_moderna$MRN,
                                                 "Moderna", "Pfizer")))),
         MfgRollUp = ifelse(is.na(Mfg) & is.na(ExpSchMfg), NA,
                            ifelse(is.na(ExpSchMfg), Mfg, ExpSchMfg)))

# Summarize schedule data for Epic sites by key stratification
epic_sched_summary <- epic_sched_to_date %>%
  filter(Status2 %in% c("Arr", "Sch") &
           ApptDate <= today) %>%
  group_by(Site,
           MfgRollUp,
           Dose,
           VaccWeek,
           ApptDate,
           Status2) %>%
  summarize(Count = n(),
            .groups = "keep") %>%
  pivot_wider(names_from = Dose,
              values_from = Count) %>%
  mutate(AllDoses = sum(Dose1, Dose2, na.rm = TRUE)) %>%
  pivot_longer(cols = c("Dose1", "Dose2", "AllDoses"),
               names_to = "Dose",
               values_to = "Count") %>%
  ungroup()

test_df <- epic_sched_summary %>%
  filter(ApptDate <= today) %>%
  group_by(Site, Dose) %>%
  summarize(Admin = sum(Count, na.rm = TRUE))

```

```{r Format MSSN Tableau data}
# Melt MSSN data to format similar to Epic sites
mssn_admin_to_date <- mssn_admin %>%
  mutate(Site = "MSSN",
         Status2 = "Arr",
         ApptDate = as.Date(ApptDate, format = "%B %d, %Y"),
         VaccWeek = as.numeric(
           floor((ApptDate - vacc_start_first_sun) / 7 +1)),
         MfgRollUp = Mfg) %>%
  filter(ApptDate <= today) %>%
  pivot_longer(cols = c("Dose1", "Dose2", "AllDoses"),
               names_to = "Dose",
               values_to = "Count")

mssn_admin_to_date <- mssn_admin_to_date[, colnames(epic_sched_summary)]
```

```{r Combine data across all sites}
# Bind MSSN data with Epic sites data
daily_sched_summary <- rbind(epic_sched_summary, mssn_admin_to_date)

daily_sched_summary <- daily_sched_summary %>%
  left_join(vacc_week_dates, by = c("VaccWeek" = "VaccWeek"))

admin_doses_by_mfg <- daily_sched_summary %>%
  group_by(Site, Dose, MfgRollUp) %>%
  summarize(AdminDoses = sum(Count, na.rm = TRUE))

write_xlsx(admin_doses_by_mfg, path = paste0(user_directory,
                                             "/AdHoc/Admin Doses By Mfg Through 03312021.xlsx"))

```

